### ISSUE TITLE
pingHost does not execute some times

### ISSUE THREAD

**Issue by asier-paz** [nospaceships/node-net-ping#56]
Hello.

The session.pingHost function unexpectedly does not call the callback without any logging at all. I am using a local network IP (172.26.0.176) and most of the time, with this IP I just see a log I print before the call to session.pingHost and then the program ends with no other output. That's so strange because in the callback of pingHost I got a lot of console logs and I am sure that at least one has to be shown before the execution finishes.

However, it does not happen that much with other ips.

Session events like "close" or "error" also don't fire when this happens. 0 logging, 0 errors.

Thanks for your work btw. Awesome module.

**Comment by stephenwvickers** [comment]
Hi @asier-paz,

Firstly, apologies for the delay, I am currently waiting for a new baby to arrive (literally yesterday) and have been quite preoccupied :)

Can you send me a complete program which emits the behaviour then I can troubleshoot further?

Thanks

Steve

**Comment by crxo1** [comment]
Hi,

i have the same problem with your module. It runs fine for some hours and then suddenly session.pingHost doesn't calls the callback.

**Comment by stephenwvickers** [comment]
Hi @crxo1 

As before, can you send me a complete program which emits the behaviour then I can troubleshoot further?

Thanks

Steve

**Comment by JeanCarlosChavarriaHughes** [comment]
Hello @stephenwvickers  . In my end the app is not working due to the following error:
```
 module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 64.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/imagineing/trash/test3/node_modules/raw-socket/index.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

I tried with npm rebuild, removed the node_modules and installed everything again but is not working.

nodejs -v
v4.8.2

**Comment by stephenwvickers** [comment]
Hi @JeanCarlosChavarriaHughes 

No, root is not required.  You just need to be able to open raw sockets.

Try usi

**Comment by crxo1** [comment]
Hi,

sorry for the late answer, i was on vacation last week.
Here is my code:

(app.js)
```
var ping      = require("./modules/ping");
var snmp      = require("./modules/snmp");
var webserver = require("./modules/webserver");

var equal     = require('fast-deep-equal');
var fs        = require('fs');
var Log       = require('log');

var options   = require("./config/options.json");
var hosts     = require("./config/hosts.json");
var snmpopt   = require("./config/snmp.json");

let targets   = [];

log           = new Log('debug', fs.createWriteStream('error.txt'));

function clone(obj) {
  var copy;

  if (null == obj || "object" != typeof obj) return obj;

  if (obj instanceof Date) {
      copy = new Date();
      copy.setTime(obj.getTime());
      return copy;
  }

  if (obj instanceof Array) {
      copy = [];
      for (var i = 0, len = obj.length; i < len; i++) {
          copy[i] = clone(obj[i]);
      }
      return copy;
  }

  if (obj instanceof Object) {
    copy = {};
    for (var attr in obj) {
        if (obj.hasOwnProperty(attr)) copy[attr] = clone(obj[attr]);
    }
    return copy;
  }
  log.error('Fehler beim kopieren!');
}

function createIPObj(data, callback) {
  var k = 0;

  for (var key in data) {
    k++;
    if (data.hasOwnProperty(key)) {
      if(data[key].ACTIVE) {
        targets.push(data[key].IP)
      }
    }
    if(k == Object.keys(data).length) {
      return callback();
    }
  }
}

function checkHosts() {
  function iterateHosts(data, callback) {
    var j = 0;
    var temphosts = clone(hosts);

    for (var key in temphosts) {
      j++;
      if (temphosts.hasOwnProperty(key)) {
        for (var i = 0; i < data.length; i++) {
          if(temphosts[key].IP == data[i].IP) {
            temphosts[key].STATUS = data[i].STATUS;
          }
        }
      }

      if(j == Object.keys(data).length) {
        return callback(temphosts);
      }
    }
  }

  ping.newPing(options, targets, function(err, data) {
    if(err != null) {
      log.error(err);

      setTimeout(function() { 
        checkHosts();
      }, 1000);
    } else {
      iterateHosts(data, function(res) {

        if(!equal(globalhosts, res)) {
          globalhosts = res;
          webserver.send('statusdata', res);
        }

        snmp.newSNMP(snmpopt.serverraum, [snmpopt.temp1, snmpopt.feucht, snmpopt.temp2, snmpopt.akku, snmpopt.signal], function(data) {
          if(!equal(globalhealth, data)) {
            globalhealth = data;
            webserver.send('healthdata', data);
          }
        });
      });

      setTimeout(function() {
        checkHosts();
      }, 1000);
    }
  });
}

globalhealth = null;
globalhosts  = clone(hosts);

createIPObj(hosts, function() {
  checkHosts();
});

```

(ping.js)
```
var ping      = require ("net-ping");
var email     = require ("./email");


module.exports = {
  newPing : function(options, targets, callback) {
    var session = ping.createSession (options);
    var j       = 0;
    var statusarr = [];

    session.on ("error", function (error) {
      return callback(error.toString, null);
    });

    for (var i = 0; i < targets.length; i++) {
      session.pingHost (targets[i], function (error, target) {
        j++;
        if (error) {
          statusarr.push({IP: target, STATUS: false});
          if(globalhosts != null) {
            for (var key in globalhosts) {
              if (globalhosts.hasOwnProperty(key)) {
                if(globalhosts[key].IP == target && globalhosts[key].STATUS === true) {
                  // email.send(target, key, error, function(err, message) {
                  //   log.info(err || message);
                  // });
                }
              }
            }
          }
        } else {
          statusarr.push({IP: target, STATUS: true});
        }
        if(j === targets.length) {
          session.close();
          return callback(null, statusarr);
        }
      });
    }
  }
}

```

**Comment by crxo1** [comment]
Hi @stephenwvickers ,

i've edited the program so that ping.createSession gets called only once when the program starts, and not everytime a ping is made. Now its running without problems. 

Thank you!
