### ISSUE TITLE
Module stopped working after I made setcap cap_net_bind_service for node

### ISSUE THREAD

**Issue by frankjoke** [nospaceships/node-net-ping#61]
I used your module to exchange the ping calls in an IoT adapter to check available network items.

It worked well until I had to allow to bind networks which I needed for another program.

Now I get the following error in net-ping when creating a service:
`

javascript.0 | 2019-01-28 17:38:08.819 | error | at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.javascript/node_modules/net-ping/index.js:545:9)
-- | -- | -- | --
javascript.0 | 2019-01-28 17:38:08.819 | error | at new Session (/opt/iobroker/node_modules/iobroker.javascript/node_modules/net-ping/index.js:101:7)
javascript.0 | 2019-01-28 17:38:08.819 | error | at Session.getSocket (/opt/iobroker/node_modules/iobroker.javascript/node_modules/net-ping/index.js:147:20)
javascript.0 | 2019-01-28 17:38:08.819 | error | at Object.exports.createSocket (/opt/iobroker/node_modules/iobroker.javascript/node_modules/raw-socket/index.js:202:9)
javascript.0 | 2019-01-28 17:38:08.819 | error | at new Socket (/opt/iobroker/node_modules/iobroker.javascript/node_modules/raw-socket/index.js:47:14)
javascript.0 | 2019-01-28 17:38:08.819 | error | Error: Operation not permitted
javascript.0 | 2019-01-28 17:38:08.819 | error | ^
javascript.0 | 2019-01-28 17:38:08.819 | error | this.wrap = new raw.SocketWrap (
javascript.0 | 2019-01-28 17:38:08.818 | error | script.js.Scripts.pingTest: /opt/iobroker/node_modules/iobroker.javascript/node_modules/raw-socket/index.js:47

`

**Comment by frankjoke** [comment]
I need to add that I normally do not run node with root permissions, your code worked without root permissions before but when I gave node the ability for 'cap_net_bind_service' your code works only as root!  
It seems that raw.SocketWrap is the reason, do you do anything different when in root or not?
