### ISSUE TITLE
raw.node is not a valid Win32 application

### ISSUE THREAD

**Issue by hallur** [nospaceships/node-net-ping#64]
When I try to run my script on Windows I get the following error:

```
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\Hallur\workspace\prototypes\icmp\node_modules\raw-socket\build\Release\raw.node is not a valid Win32 application.
\\?\C:\Users\Hallur\workspace\prototypes\icmp\node_modules\raw-socket\build\Release\raw.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Hallur\workspace\prototypes\icmp\node_modules\raw-socket\index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

This is my code:

```const ping = require('net-ping');

(() => {
  const session = ping.createSession({
    networkProtocol: ping.NetworkProtocol.IPv4,
    packetSize: 16,
    retries: 1,
    sessionId: (process.pid % 65535),
    timeout: 2000,
    ttl: 128,
  });

  session.pingHost('8.8.8.8', (err, target) => {
    if (err) {
      console.error('Error');
      console.error(err);
    } else {
      console.log('Success');
      console.log(target);
    }
  });
})();
```

Does this package not work for Windows?

**Comment by stephenwvickers** [comment]
Hi, yes the package does work on Windows.

How are you using this module, i.e. what platform or framework?

**Comment by sophyawei** [comment]
I have a similar problem with raw.node file.

I'm working on MacOS and using Quasar framework to try to make a hybrid mobile app. 

I'm trying out your library and encounter this error:
`Uncaught Error: Cannot open /node_modules/raw-socket/build/Release/raw.node: TypeError: Cannot read property 'dlopen' of undefined
    at Object.eval (raw.node?6eaf:1)
    at eval (raw.node:2)
    at Object../node_modules/raw-socket/build/Release/raw.node (app.js:9219)
    at __webpack_require__ (app.js:725)
    at fn (app.js:102)
    at Object.eval (index.js?3fb2:4)
    at eval (index.js:218)
    at Object../node_modules/raw-socket/index.js (app.js:9230)
    at __webpack_require__ (app.js:725)
    at fn (app.js:102)`

this is my code:
`import ping from 'net-ping'
var session = ping.createSession()
session.pingHost('8.8.8.8', function (error, target) {
        if (error) {
          if (error instanceof ping.RequestTimedOutError) {
            console.log (target + ": Not alive")
          } else {
            console.log (target + ": " + error.toString ())
          }
        } else {
          console.log (target + ": Alive")
        }
    })`

I reinstall this package 2 times and still have raw.node error. Is there another way to fix raw.node error? thank you.
