### ISSUE TITLE
Can't create IPv6 session on macOS

### ISSUE THREAD

**Issue by mohd-akram** [nospaceships/node-net-ping#65]
Running:

```javascript
const netPing = require('net-ping');

const ipv6Session = netPing.createSession({
  networkProtocol: netPing.NetworkProtocol.IPv6
});
```

fails with:

```
Error: Operation not permitted
    at new Socket (/Users/mohamed/Documents/test/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/Users/mohamed/Documents/test/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/Users/mohamed/Documents/test/node_modules/net-ping/index.js:147:20)
    at new Session (/Users/mohamed/Documents/test/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/Users/mohamed/Documents/test/node_modules/net-ping/index.js:545:9)
```

**Comment by stephenwvickers** [comment]
Hi, I believe the error is quite clear, you need to have permissions to be able to open raw sockets on your platform.

**Comment by mohd-akram** [comment]
That's not necessary for ping though. See [Apple's implementation](https://github.com/apple-open-source/macos/blob/10.14.1/network_cmds/ping6.tproj/ping6.c). I saw that you do something similar in `node-raw-socket`, but I'm not sure why it doesn't work for IPv6.

**Comment by stephenwvickers** [comment]
@mohd-akram I am not sure, it should be falling back to UDP for both IPv4 and IPv6.

Perhaps the strace equivilant on Mac would show what is actually being called?

**Comment by mohd-akram** [comment]
I think I found the problem. The check [here](https://github.com/nospaceships/node-raw-socket/blob/5c63103fd953d94b1333a95293fb2e9cc4eeab4b/src/raw.cc#L319) is only for `IPPROTO_ICMP` and not `IPPROTO_ICMPV6`.
