### ISSUE TITLE
Getting Error with code from docs

### ISSUE THREAD

**Issue by markomiljkovic** [nospaceships/node-net-ping#68]
Hi, I'm using your plugin net-ping, but I'm having trouble making it work correctly

```
var ping = require ("net-ping");
const session = ping.createSession();

session.pingHost('http://google.com', function (error, target) {
        if (error)
            console.log(target + ": " + error.toString());
        else
            console.log(target + ": Alive");
});
```

And when I run the Node app, I get the following error:

```
UNCAUGHT EXCEPTION - keeping process alive: Error: Operation not permitted
    at new Socket (/work/Projects/ELS/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/work/Projects/ELS/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/work/Projects/ELS/node_modules/net-ping/index.js:147:20)
    at new Session (/work/Projects/ELS/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/work/Projects/ELS/node_modules/net-ping/index.js:545:9)
    at Object.<anonymous> (/work/Projects/ELS/server/index.js:9:22)
```

**Comment by stephenwvickers** [comment]
Hi @markomiljkovic 

You can't URLs or domain names, only IPv4 or IPv6 addresses.

Steve
