### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by Freszmun** [nospaceships/node-net-ping#69]
When I'm creating new session:
.../node_modules/raw-socket/index.js:47
        this.wrap = new raw.SocketWrap (
                    ^

Error: Operation not permitted
    at Error (native)
    at new Socket (.../node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (.../node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (.../node_modules/net-ping/index.js:147:20)
    at new Session (.../node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (.../node_modules/net-ping/index.js:545:9)
    at Object.<anonymous> (.../app.js:2:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)    at Module.load (module.js:494:32)
-------------------------------
Is possible to fix that?

**Comment by stephenwvickers** [comment]
Hi @Freszmun 

It is likely you do not have permissions to open raw sockets.

Please either run the tool as a user who does have permissions, or consider using the setcap command.

Steve
