### ISSUE TITLE
Unable to install net-ping

### ISSUE THREAD

**Issue by debjava** [nospaceships/node-net-ping#73]
While installing net-ping, I get the following error. I have both visual studio and python properly installed.

```
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\devsoftwares\nodejs10\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at findVisualStudio2013 (C:\devsoftwares\nodejs10\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\devsoftwares\nodejs10\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at findVisualStudio2015 (C:\devsoftwares\nodejs10\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14)
gyp ERR! stack     at regSearchKeys (C:\devsoftwares\nodejs10\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16)
gyp ERR! stack     at regGetValue (C:\devsoftwares\nodejs10\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7)
gyp ERR! stack     at C:\devsoftwares\nodejs10\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\devsoftwares\\nodejs10\\node.exe" "C:\\devsoftwares\\nodejs10\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\javascriptdev11\inireader\node_modules\raw-socket
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by stephenwvickers** [comment]
Hi @debjava this has nothing to do with the module itself, for some reason node-gyp/npm cannot find your visual studio studio installation as per the message:

> gyp ERR! stack Error: Could not find any Visual Studio installation to use

**Comment by debjava** [comment]
I have resolved it. Thanks for your support.
