### ISSUE TITLE
Unable to execute net-ping

### ISSUE THREAD

**Issue by zachjonesnoel** [nospaceships/node-net-ping#82]
Installed net-ping v1.2.3 from npm. I executed this locally on my node environment, worked fine.

But when executing this from AWS Lambda function, getting the below error - 
```
{
  "errorType": "Error",
  "errorMessage": "/opt/nodejs/node_modules/raw-socket/build/Release/raw.node: invalid ELF header",
  "trace": [
    "Error: /opt/nodejs/node_modules/raw-socket/build/Release/raw.node: invalid ELF header",
    "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)",
    "    at Module.load (internal/modules/cjs/loader.js:937:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
    "    at Module.require (internal/modules/cjs/loader.js:961:19)",
    "    at require (internal/modules/cjs/helpers.js:92:18)",
    "    at Object.<anonymous> (/opt/nodejs/node_modules/raw-socket/index.js:4:11)",
    "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
    "    at Module.load (internal/modules/cjs/loader.js:937:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)"
  ]
}
``` 
I checked AWS Lambda had a limitation so have raised a [feature request](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/issues/32). 

I was getting the same error when running it from VueJS application also. So I think that might be more of the package issue.

**Comment by stephenwvickers** [comment]
We don't support that environment, I am not sure even how that works and how it supports compiled Node.js modules.
